name: Mirror image after commit

on:
  push:
    branches: ["master"]
  workflow_dispatch:

env:
  SOURCE_REPO: louislam/uptime-kuma
  TARGET_REPO: ghcr.io/yabloky/uptime-kuma

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Install jq
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Get last 3 versions
        id: versions
        run: |
          VERSIONS=$(curl -s https://api.github.com/repos/${SOURCE_REPO}/releases | jq -r '.[0:3] | .[].tag_name')
          echo "versions<<EOF" >> $GITHUB_OUTPUT
          echo "$VERSIONS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "Found versions:"
          echo "$VERSIONS"

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Mirror last 3 versions
        run: |
          while read -r VERSION; do
            [ -z "$VERSION" ] && continue
            echo "-----> Mirroring version: $VERSION"
            docker pull "${{ env.SOURCE_REPO }}:$VERSION"
            docker tag  "${{ env.SOURCE_REPO }}:$VERSION" "${{ env.TARGET_REPO }}:$VERSION"
            docker push "${{ env.TARGET_REPO }}:$VERSION"
          done <<< "${{ steps.versions.outputs.versions }}"

          # Тег latest — для самой свежей версии
          LATEST=$(echo "${{ steps.versions.outputs.versions }}" | head -n 1)
          docker tag "${{ env.SOURCE_REPO }}:$LATEST" "${{ env.TARGET_REPO }}:latest"
          docker push "${{ env.TARGET_REPO }}:latest"
