name: Mirror image after commit

on:
  push:
    branches: ["master"]
  workflow_dispatch:

env:
  SOURCE_REPO: louislam/uptime-kuma
  TARGET_REPO: ghcr.io/yabloky/uptime-kuma

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Get latest tag from upstream
        id: get_tag
        run: |
          TAG=$(curl -s "https://api.github.com/repos/${SOURCE_REPO}/releases/latest" | jq -r .tag_name)
          # if upstream returns null/empty, keep it empty (we'll fallback later)
          echo "tag=$TAG" >> "${GITHUB_OUTPUT}"
          echo "Latest version detected: $TAG"

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull and push image
        run: |
          SOURCE="${SOURCE_REPO}"
          TARGET="${TARGET_REPO}"
          TAG="${{ steps.get_tag.outputs.tag }}"
          if [ -z "$TAG" ] || [ "$TAG" = "null" ]; then
            echo "No upstream tag found, falling back to 'latest'"
            TAG="latest"
          fi
          echo "Using SOURCE=${SOURCE}:${TAG} -> TARGET=${TARGET}:${TAG} (also tagging :latest)"
          docker pull "${SOURCE}:${TAG}"
          docker tag  "${SOURCE}:${TAG}" "${TARGET}:${TAG}"
          docker tag  "${SOURCE}:${TAG}" "${TARGET}:latest"
          docker push "${TARGET}:${TAG}"
          docker push "${TARGET}:latest"

      - name: Show pushed image version
        run: echo "✅ Mirrored version: ${{ steps.get_tag.outputs.tag }}"
